return {
  dashboard = {
    zettel_tree = "▣",
    in_tree = "□",
    zettel_note = "◇",
    in_note = "◆",
    recent = "◷",
    search = "⌕",
    quit = "×",
  },
  markdown = {
    headings = { "# ", "## ", "### ", "#### ", "##### ", "###### " },
    unchecked = "☐ ",
    checked = "☑ ",
    note = "i",
    tip = "✓",
    important = "!",
    warning = "!",
    caution = "×",
    image = "img ",
    email = "@ ",
    hyperlink = "↗ ",
    wiki = "[[",
  },
  tree = {
    file = "File",
    buffers = "Bufs",
    git = "Git",
    collapsed = "▸",
    expanded = "▾",
    folder_closed = "▣",
    folder_open = "▾",
    folder_empty = "□",
    file_default = "•",
    modified = "●",
  },
  git = {
    added = "+",
    deleted = "-",
    modified = "~",
    renamed = "→",
    untracked = "?",
    ignored = "·",
    unstaged = "!",
    staged = "✓",
    conflict = "×",
  },
}
