local M = {}

local colors = require("upsc_notes.astroui.palette")

local function set(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.apply()
  set("Normal", { fg = colors.fg, bg = colors.bg })
  set("NormalFloat", { fg = colors.fg, bg = colors.bg_float })
  set("FloatBorder", { fg = colors.border, bg = colors.bg_float })
  set("FloatTitle", { fg = colors.blue, bg = colors.bg_float, bold = true })
  set("CursorLine", { bg = colors.bg_line })
  set("Visual", { bg = "#3b4261" })
  set("Search", { fg = colors.bg, bg = colors.yellow, bold = true })
  set("IncSearch", { fg = colors.bg, bg = colors.peach, bold = true })
  set("Pmenu", { fg = colors.fg, bg = colors.bg_float })
  set("PmenuSel", { fg = colors.bg, bg = colors.blue, bold = true })
  set("LineNr", { fg = colors.muted })
  set("CursorLineNr", { fg = colors.peach, bold = true })
  set("SignColumn", { bg = colors.bg })
  set("StatusLine", { fg = colors.fg, bg = colors.bg_alt })
  set("StatusLineNC", { fg = colors.muted, bg = colors.bg_alt })
  set("WinSeparator", { fg = colors.border, bg = colors.bg })
  set("NonText", { fg = colors.muted })

  set("UpscDashboardHeader", { fg = colors.blue, bold = true })
  set("UpscDashboardButton", { fg = colors.fg })
  set("UpscDashboardShortcut", { fg = colors.peach, bold = true })
  set("UpscDashboardFooter", { fg = colors.muted })

  set("markdownH1", { fg = colors.blue, bold = true })
  set("markdownH2", { fg = colors.mauve, bold = true })
  set("markdownH3", { fg = colors.peach, bold = true })
  set("markdownH4", { fg = colors.green, bold = true })
  set("markdownH5", { fg = colors.cyan, bold = true })
  set("markdownH6", { fg = colors.subtle, bold = true })
  set("markdownHeadingDelimiter", { fg = colors.muted })
  set("markdownBold", { fg = colors.fg, bold = true })
  set("markdownItalic", { fg = colors.subtle, italic = true })
  set("markdownCode", { fg = colors.green, bg = colors.bg_alt })
  set("markdownCodeBlock", { fg = colors.green })
  set("markdownListMarker", { fg = colors.peach })
  set("markdownBlockquote", { fg = colors.subtle, italic = true })
  set("markdownLinkText", { fg = colors.blue, underline = true })
  set("markdownUrl", { fg = colors.cyan, underline = true })
  set("markdownRule", { fg = colors.border })

  set("RenderMarkdownH1", { fg = colors.blue, bold = true })
  set("RenderMarkdownH2", { fg = colors.mauve, bold = true })
  set("RenderMarkdownH3", { fg = colors.peach, bold = true })
  set("RenderMarkdownH4", { fg = colors.green, bold = true })
  set("RenderMarkdownH5", { fg = colors.cyan, bold = true })
  set("RenderMarkdownH6", { fg = colors.subtle, bold = true })
  set("RenderMarkdownH1Bg", { bg = "#1c2f4f" })
  set("RenderMarkdownH2Bg", { bg = "#2b2442" })
  set("RenderMarkdownH3Bg", { bg = "#34283b" })
  set("RenderMarkdownH4Bg", { bg = "#213329" })
  set("RenderMarkdownH5Bg", { bg = "#1d3038" })
  set("RenderMarkdownH6Bg", { bg = colors.bg_alt })
  set("RenderMarkdownCode", { fg = colors.green, bg = colors.bg_alt })
  set("RenderMarkdownCodeInline", { fg = colors.yellow, bg = colors.bg_alt })
  set("RenderMarkdownCodeBorder", { fg = colors.border, bg = colors.bg_alt })
  set("RenderMarkdownCodeFallback", { fg = colors.green, bg = colors.bg_alt })
  set("RenderMarkdownBullet", { fg = colors.peach })
  set("RenderMarkdownDash", { fg = colors.border })
  set("RenderMarkdownQuote", { fg = colors.mauve, italic = true })
  set("RenderMarkdownTableHead", { fg = colors.blue, bold = true })
  set("RenderMarkdownTableRow", { fg = colors.fg })
  set("RenderMarkdownTableFill", { bg = colors.bg })
  set("RenderMarkdownLink", { fg = colors.blue, underline = true })
  set("RenderMarkdownWikiLink", { fg = colors.cyan, underline = true })
  set("RenderMarkdownUnchecked", { fg = colors.muted })
  set("RenderMarkdownChecked", { fg = colors.green })
  set("RenderMarkdownInfo", { fg = colors.blue })
  set("RenderMarkdownSuccess", { fg = colors.green })
  set("RenderMarkdownHint", { fg = colors.mauve })
  set("RenderMarkdownWarn", { fg = colors.yellow })
  set("RenderMarkdownError", { fg = colors.red })

  set("SnacksPicker", { fg = colors.fg, bg = colors.bg_float })
  set("SnacksPickerBorder", { fg = colors.border, bg = colors.bg_float })
  set("SnacksPickerTitle", { fg = colors.blue, bg = colors.bg_float, bold = true })
  set("SnacksPickerBoxBorder", { fg = colors.border, bg = colors.bg_float })
  set("SnacksPickerInput", { fg = colors.fg, bg = colors.bg_alt })
  set("SnacksPickerInputBorder", { fg = colors.blue, bg = colors.bg_alt })
  set("SnacksPickerPrompt", { fg = colors.peach, bg = colors.bg_alt, bold = true })
  set("SnacksPickerInputSearch", { fg = colors.yellow, bg = colors.bg_alt, bold = true })
  set("SnacksPickerList", { fg = colors.fg, bg = colors.bg_float })
  set("SnacksPickerListBorder", { fg = colors.border, bg = colors.bg_float })
  set("SnacksPickerListCursorLine", { fg = colors.fg, bg = colors.bg_line })
  set("SnacksPickerPreview", { fg = colors.fg, bg = colors.bg })
  set("SnacksPickerPreviewBorder", { fg = colors.border, bg = colors.bg })
  set("SnacksPickerPreviewCursorLine", { bg = colors.bg_line })
  set("SnacksPickerMatch", { fg = colors.peach, bold = true })
  set("SnacksPickerSearch", { fg = colors.bg, bg = colors.yellow, bold = true })
  set("SnacksPickerDir", { fg = colors.muted })
  set("SnacksPickerDirectory", { fg = colors.blue, bold = true })
  set("SnacksPickerFile", { fg = colors.fg })
  set("SnacksPickerPathHidden", { fg = colors.muted })
  set("SnacksPickerPathIgnored", { fg = colors.muted })
  set("SnacksPickerRow", { fg = colors.green })
  set("SnacksPickerCol", { fg = colors.subtle })
  set("SnacksPickerDelim", { fg = colors.muted })
  set("SnacksPickerTotals", { fg = colors.subtle })
  set("SnacksPickerComment", { fg = colors.muted, italic = true })
  set("SnacksPickerSelected", { fg = colors.green, bold = true })
  set("SnacksPickerUnselected", { fg = colors.muted })
  set("SnacksPickerSpinner", { fg = colors.peach })
  set("SnacksPickerPickWin", { fg = colors.bg, bg = colors.peach, bold = true })
  set("SnacksPickerPickWinCurrent", { fg = colors.bg, bg = colors.green, bold = true })

  set("NeoTreeNormal", { fg = colors.fg, bg = colors.bg_alt })
  set("NeoTreeNormalNC", { fg = colors.fg, bg = colors.bg_alt })
  set("NeoTreeWinSeparator", { fg = colors.border, bg = colors.bg_alt })
  set("NeoTreeDirectoryName", { fg = colors.blue, bold = true })
  set("NeoTreeDirectoryIcon", { fg = colors.blue })
  set("NeoTreeFileName", { fg = colors.fg })
  set("NeoTreeFileNameOpened", { fg = colors.peach, bold = true })
  set("NeoTreeCursorLine", { bg = colors.bg_line })
  set("NeoTreeRootName", { fg = colors.mauve, bold = true })

  set("WhichKeyFloat", { bg = colors.bg_float })
  set("WhichKeyBorder", { fg = colors.border, bg = colors.bg_float })
  set("WhichKey", { fg = colors.blue })
  set("WhichKeyGroup", { fg = colors.mauve })
  set("WhichKeyDesc", { fg = colors.fg })
end

function M.setup()
  local group = vim.api.nvim_create_augroup("UpscNotesUi", { clear = true })
  vim.api.nvim_create_autocmd("ColorScheme", {
    group = group,
    callback = M.apply,
  })
  M.apply()
end

return M
